### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by hemberger** [bubba0077/Trivia#198]
Ubuntu 15.10, openjdk-7-jre and icedtea-netx for javaws. Am I missing some java software, or is this a legitimate issue?

```
netx: Launch Error: Could not launch JNLP file. ( (java/time/ZoneId (java.time.ZoneId)))
net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute javaws/browser from the command line and send a bug report.
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:570)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:904)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:564)
	... 1 more
Caused by: java.lang.NoClassDefFoundError: java/time/ZoneId
	at net.bubbaland.trivia.client.TriviaClient.<init>(TriviaClient.java:60)
	at net.bubbaland.trivia.client.TriviaGUI.<init>(TriviaGUI.java:175)
	at net.bubbaland.trivia.client.TriviaGUI.main(TriviaGUI.java:259)
	... 6 more
Caused by: java.lang.ClassNotFoundException: java.time.ZoneId
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1536)
	... 9 more
```

**Comment by bubba0077** [comment]
You need openjdk-8-jre, as noted in my e-mail. May still fail because there is no IcedTea for Java 8 yet, but that would be good to know.

**Comment by hemberger** [comment]
Probably not surprising, given your last comment, but I get the same error after installing the openjdk-8-jre package. I don't know how to open a jnlp without javaws.

**Comment by bubba0077** [comment]
Try this:

sudo add-apt-repository ppa:maarten-fonville/ppa
sudo apt-get update
sudo apt-get install icedtea-8-plugin

**Comment by bubba0077** [comment]
Alternatively, install Oracle's JRE.

**Comment by wthrowe** [comment]
Same here.  As noted above, I don't think IcedTea supports Java 8 yet.  (Seems to have been in the "coming any moment now" state for the past few years, from the small amount of attention I've been paying to it.)

And no `apt-get` here.  Wrong distro.

**Comment by bubba0077** [comment]
Have you tried the Oracle JRE?

**Comment by hemberger** [comment]
After this change, I get the following error after the "Enter user name" box pops up:
```
netx: Launch Error: Could not launch JNLP file. ( (java/util/function/IntPredicate (java.util.function.IntPredicate)))
net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute javaws/browser from the command line and send a bug report.
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:570)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:904)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:564)
	... 1 more
Caused by: java.lang.NoClassDefFoundError: java/util/function/IntPredicate
	at net.bubbaland.trivia.client.OpenQuestionsPanel.<init>(OpenQuestionsPanel.java:129)
	at net.bubbaland.trivia.client.WorkflowPanel.<init>(WorkflowPanel.java:47)
	at net.bubbaland.trivia.client.TriviaGUI.getTab(TriviaGUI.java:291)
	at net.bubbaland.trivia.client.TriviaFrame.<init>(TriviaFrame.java:121)
	at net.bubbaland.trivia.client.TriviaGUI.<init>(TriviaGUI.java:221)
	at net.bubbaland.trivia.client.TriviaGUI.main(TriviaGUI.java:259)
	... 6 more
Caused by: java.lang.ClassNotFoundException: java.util.function.IntPredicate
	at net.sourceforge.jnlp.runtime.JNLPClassLoader.loadClass(JNLPClassLoader.java:1536)
	... 12 more
```

**Comment by bubba0077** [comment]
I've recompiled a new client using JRE 7 (I thought I had already). Try now.
