### ISSUE TITLE
If the is a visual trivia higher than the maximum number, the open questions panel pukes exceptions

### ISSUE THREAD

**Issue by hemberger** [bubba0077/Trivia#204]
This went away after I relogged and/or Walter changed something, but here is one of the many exceptions I got, in case it's useful. None of the questions were displaying correctly, nor were any of the buttons working as expected.
```
Exception in thread "AWT-EventQueue-1" java.lang.ArrayIndexOutOfBoundsException: 0
	at net.bubbaland.trivia.Trivia.getVisualTriviaUsed(Trivia.java:1191)
	at net.bubbaland.trivia.client.OpenQuestionsPanel.updateGUI(OpenQuestionsPanel.java:196)
	at net.bubbaland.trivia.client.WorkflowPanel.updateGUI(WorkflowPanel.java:103)
	at net.bubbaland.trivia.client.TriviaFrame.updateGUI(TriviaFrame.java:930)
	at net.bubbaland.trivia.client.TriviaGUI$5.run(TriviaGUI.java:409)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Exception in thread "AWT-EventQueue-1" java.lang.ArrayIndexOutOfBoundsException: 0
	at net.bubbaland.trivia.Trivia.getVisualTriviaUsed(Trivia.java:1191)
	at net.bubbaland.trivia.client.OpenQuestionsPanel.updateGUI(OpenQuestionsPanel.java:196)
	at net.bubbaland.trivia.client.WorkflowPanel.updateGUI(WorkflowPanel.java:103)
	at net.bubbaland.trivia.client.TriviaFrame.updateGUI(TriviaFrame.java:930)
	at net.bubbaland.trivia.client.TriviaGUI$5.run(TriviaGUI.java:409)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:706)
	at java.awt.EventQueue$3.run(EventQueue.java:704)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by bubba0077** [comment]
This is an issue with having the number of visual trivia set to a lower number than a visual trivia number used in a question.
