### ISSUE TITLE
Exceptions on Trivia > Load Default Settings

### ISSUE THREAD

**Issue by wthrowe** [bubba0077/Trivia#215]
```
Exception in thread "AWT-EventQueue-1" java.lang.ClassCastException: javax.swing.JViewport cannot be cast to javax.swing.JPanel
        at net.bubbaland.trivia.client.AnswerQueuePanel$AnswerQueueSubPanel.loadProperties(AnswerQueuePanel.java:1226)
        at net.bubbaland.trivia.client.AnswerQueuePanel.loadProperties(AnswerQueuePanel.java:574)
        at net.bubbaland.trivia.client.WorkflowPanel.loadProperties(WorkflowPanel.java:92)
        at net.bubbaland.trivia.client.TriviaFrame.loadProperties(TriviaFrame.java:768)
        at net.bubbaland.trivia.client.TriviaGUI.loadProperties(TriviaGUI.java:332)
        at net.bubbaland.trivia.client.TriviaGUI.resetProperties(TriviaGUI.java:387)
        at net.bubbaland.trivia.client.TriviaFrame.actionPerformed(TriviaFrame.java:620)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2341)
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
        at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
        at java.awt.Component.processMouseEvent(Component.java:6516)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3312)
        at java.awt.Component.processEvent(Component.java:6281)
        at java.awt.Container.processEvent(Container.java:2229)
        at java.awt.Component.dispatchEventImpl(Component.java:4872)
        at java.awt.Container.dispatchEventImpl(Container.java:2287)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
        at java.awt.Container.dispatchEventImpl(Container.java:2273)
        at java.awt.Window.dispatchEventImpl(Window.java:2719)
        at java.awt.Component.dispatchEvent(Component.java:4698)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:747)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
        at java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.awt.EventQueue$4.run(EventQueue.java:718)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:717)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
Exception in thread "AWT-EventQueue-1" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "AWT-EventQueue-1" java.lang.ArrayIndexOutOfBoundsException
Exception in thread "AWT-EventQueue-1" java.lang.ArrayIndexOutOfBoundsException
```

**Comment by bubba0077** [comment]
Can't reproduce at this point. Other changes to loadDefaults may have fixed this as well.
