### ISSUE TITLE
User list blanks

### ISSUE THREAD

**Issue by wthrowe** [bubba0077/Trivia#222]
The user list blanked and refreshed repeatedly.  The following exception was in my log, although I'm not sure it was related:

```
Exception in thread "AWT-EventQueue-1" java.lang.ArrayIndexOutOfBoundsException: 6
        at javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1367)
        at javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(BasicListUI.java:1310)
        at javax.swing.plaf.basic.BasicListUI.getPreferredSize(BasicListUI.java:577)
        at javax.swing.JComponent.getPreferredSize(JComponent.java:1652)
        at javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:790)
        at java.awt.Container.layout(Container.java:1503)
        at java.awt.Container.doLayout(Container.java:1492)
        at java.awt.Container.validateTree(Container.java:1688)
        at java.awt.Container.validate(Container.java:1623)
        at javax.swing.RepaintManager$2.run(RepaintManager.java:691)
        at javax.swing.RepaintManager$2.run(RepaintManager.java:689)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
        at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:688)
        at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1676)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
        at java.awt.EventQueue.access$300(EventQueue.java:103)
        at java.awt.EventQueue$3.run(EventQueue.java:706)
        at java.awt.EventQueue$3.run(EventQueue.java:704)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:77)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by bubba0077** [comment]
Nope, didn't work.
